version: '3.8'

services:
    auth_service:
        container_name: auth_go
        restart: always
        build:
          dockerfile: dev.Dockerfile
        ports:
            - 50000:8080
        volumes:
            - ./:/app
            
networks:
  default:
    name: cp-backend 
    external: true