version: '3.8'

services:
    auth_service:
        container_name: auth_go
        restart: always
        build:
          dockerfile: dev.Dockerfile
        ports:
            - 8081:8081
        volumes:
            - ./:/app
        networks:
            - auth_service_network
networks:
    auth_service_network:
        external:
            name: users_network
