// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package userQ

import (
	"github.com/google/uuid"
)

type User struct {
	ID      uuid.UUID `db:"id" json:"id" validate:"omitempty"`
	Name    string    `db:"name" json:"name" validate:"required,max=50"`
	Surname string    `db:"surname" json:"surname" validate:"required,max=50"`
	Email   string    `db:"email" json:"email" validate:"required,email"`
}
