// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package userQ

import (
	"context"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :execrows
UPDATE users SET is_active = TRUE WHERE ID = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const create = `-- name: Create :exec
INSERT INTO users (
    email, hashed_password, name, surname
) VALUES (
    $1, $2, $3, $4
)
`

type CreateParams struct {
	Email          string `db:"email" json:"email"`
	HashedPassword string `db:"hashed_password" json:"hashedPassword"`
	Name           string `db:"name" json:"name"`
	Surname        string `db:"surname" json:"surname"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.ExecContext(ctx, create,
		arg.Email,
		arg.HashedPassword,
		arg.Name,
		arg.Surname,
	)
	return err
}

const deleteByEmail = `-- name: DeleteByEmail :execrows
DELETE FROM users WHERE email = $1
`

func (q *Queries) DeleteByEmail(ctx context.Context, email string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteByEmail, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteById = `-- name: DeleteById :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAll = `-- name: GetAll :many
SELECT id, email, hashed_password, name, surname, role, created_at, last_login_at, is_active FROM users
`

func (q *Queries) GetAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.Name,
			&i.Surname,
			&i.Role,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllByNames = `-- name: GetAllByNames :many
SELECT id, email, hashed_password, name, surname, role, created_at, last_login_at, is_active FROM users
ORDER BY name
`

func (q *Queries) GetAllByNames(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllByNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.Name,
			&i.Surname,
			&i.Role,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, hashed_password, name, surname, role, created_at, last_login_at, is_active FROM users
WHERE email = $1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Name,
		&i.Surname,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.IsActive,
	)
	return i, err
}

const getById = `-- name: GetById :one
SELECT id, email, hashed_password, name, surname, role, created_at, last_login_at, is_active FROM users
WHERE id = $1
`

func (q *Queries) GetById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Name,
		&i.Surname,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.IsActive,
	)
	return i, err
}
