version: '3.8'

services:
    gateway:
        container_name: gateway
        restart: always
        build:
          context: ../
          dockerfile: ./gateway/dev.Dockerfile
        ports:
            - 3000:8082
        volumes:
            - ./:/app/service
            - ../shared/:/app/shared
            
networks:
  default:
    name: cp-backend 
    external: true
