filebeat.inputs:
- type: log
  paths:
  - /logs/*.log

processors:
  - decode_json_fields:
      fields: ["message"]
      max_depth: 2
      target: "json"
      overwrite_keys: false
      add_error_key: true

json.keys_under_root: true
json.message_key: log

output.elasticsearch:
  hosts: ["elasticsearch:9200"] 