version: '3.8'

services:
    $serviceName_service:
        container_name: $serviceName_go
        restart: always
        build:
          context: ../
          dockerfile: dev.Dockerfile
        ports:
            - $PORT:8080
        volumes:
            - ./:/app

networks:
  default:
    name: cp-backend 
    external: true