version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    container_name: users-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./config/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}      
volumes:
  data:
  config:
