version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "userDB"
        json_tags_case_style: "camel"
        emit_json_tags: true
        emit_db_tags: true
        overrides: 
          - column: users.id
            go_struct_tag: validate:"omitempty"
          - column: users.name
            go_struct_tag: validate:"required,max=50"
          - column: users.hashedPassword
            go_struct_tag: validate:"required,min=6,max=256"
          - column: users.surname
            go_struct_tag: validate:"required,max=50"
          - column: users.email
            go_struct_tag: validate:"required,email"
          - column: users.role
            go_struct_tag: validate:"required"
          - column: users.is_active
            go_struct_tag: validate:"omitempty"
        out: "../../cmd/db/queries/user"