version: "3.8"
services:
  users_db:
    image: postgres:15.1-alpine
    container_name: users_db
    restart: always
    env_file:
      - ./dev.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./config/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 4000:5432


  redis_cache:
    image: redis:7.0.5-alpine
    container_name: redis_cache
    restart: always
    volumes:
      - ./data/cache:/data

  users_service:
    container_name: users_go
    depends_on:
      - redis_cache
      - users_db
    restart: always
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 50001:8081
    volumes:
      - ./:/app

networks:
  default:
    name: cp-backend 
    external: true
    
volumes:
  data:
  config:
