version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    container_name: users-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./config/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - users_network

  redis-cache:
    image: redis:7.0.5-alpine
    container_name: users-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache:/data
    networks:
      - users_network

  users_service:
    container_name: users_go
    restart: always
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app

networks:
  users_network:
    name: users_network
    
volumes:
  data:
  config:
